name: onenote-desktop # you probably want to 'snapcraft register <name>'
base: core18
version: '1.1.1' # just for humans, typically '1.2+git' or '1.3.2'
icon: src/images/icon.png
summary: OneNote Desktop Client for Linux # 79 char long summary
description: |
  Unofficial OneNote app for Linux.
  OneNote.com wrapped in electron application and packaged for Linux

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  onenote-desktop:
    command: onenote-desktop
    plugs:
    - browser-support
    - gnome-3-28-1804
    - gtk-3-themes
    - icon-themes
    - sound-themes
    - desktop
    - desktop-legacy
    - gsettings
    - home
    - network
    - opengl
    - pulseaudio
    - unity7
    - x11
    common-id: org.anuj.onenote-desktop
    # desktop: "usr/share/applications/onenote-desktop.desktop"

parts:
  onenote-desktop:
    source: dist/onenote.tar.gz
    # source: dist/OneNote-1.1.1-amd64.deb
    # source-type: deb
    # See 'snapcraft plugins'
    plugin: dump
    # source: .
    # plugin: nodejs
    # stage-packages: [libc6, libcanberra-gtk-module]

plugs:
  gnome-3-28-1804:
    content: gnome-3-28-1804
    interface: content
    target: $SNAP/extra-libs
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    content: gtk-3-themes
    interface: content
    target: $SNAP/extra-libs
    default-provider: gtk-common-themes
  icon-themes:
    content: icon-themes
    interface: content
    target: $SNAP/extra-libs
    default-provider: gtk-common-themes
  sound-themes:
    content: sound-themes
    interface: content
    target: $SNAP/extra-libs
    default-provider: gtk-common-themes
